name: CI Workflow

on:
  pull_request:     # Se ejecuta para cualquier pull request en cualquier rama

jobs:
  build:
    name: Compile, Format Check, and Code Analysis
    runs-on: ubuntu-latest  # Usamos una m치quina virtual con Ubuntu

    steps:
    # 1. Clonar el repositorio
    - name: Checkout the repository
      uses: actions/checkout@v3

    # 2. Instalar dependencias necesarias para clang-format, cppcheck, make y gcc-arm-none-eabi
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format cppcheck make gcc-arm-none-eabi

    # 3. Verificar el formato del archivo main.c con clang-format
    - name: Run clang-format on main.c
      run: |
        clang-format --dry-run --Werror main.c

    # 4. Ejecutar an치lisis est치tico del c칩digo con cppcheck
    - name: Run cppcheck
      run: |
        cppcheck --enable=all --inconclusive --error-exitcode=1 .

    # 5. Compilar el proyecto utilizando Makefile
    - name: Build the project
      run: |
        make all
